services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: N8N
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment: 
      GENERIC_TIMEZONE: "Europe/Paris"
      TZ: "Europe/Paris"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - portfolio_portfolio_network

volumes:
  n8n_data:


