# Inspired by TaouMou
# github.com/TaouMou/starship-presets

format = """
[╭─](fg:arrow)\
$os$username\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$time\
$cmd_duration
[╰─](fg:arrow)$character
"""

add_newline = true

palette = "old"

[palettes.old]
arrow = "#353535"
os = "#3778BF"
os_admin = "#6A040F"
directory = "#3F37C9"
git = "#B02B10"
git_status = "#8B1D2C"
python = "#3776AB"
node = "#3EB049"
time = "#177E89"
duration = "#FFD23F"
text_color = "#EDF2F4"

# ─────────────────────────────
# MODULES
# ─────────────────────────────

[os]
format = "[](fg:os)[$symbol]($style)"
style = "bg:os fg:text_color"
disabled = false

[os.symbols]
Alpine = " "
Android = " "
Arch = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
Ubuntu = " "
Windows = " "
Unknown = " "

[username]
style_user = 'bg:os fg:text_color'
style_root = 'bg:os_admin fg:text_color'
format = '[$user]($style)[](fg:os)'
show_always = true
disabled = false

[directory]
format = " [](fg:directory)[  $path]($style)[](fg:directory)"
style = "bg:directory fg:text_color"
truncation_length = 1
truncate_to_repo = true

[git_branch]
format = " [](fg:git)[ $branch]($style)[](fg:git)"
style = "bg:git fg:text_color"

[git_status]
format = '([ ](fg:git_status)[$all_status$ahead_behind ]($style)[](fg:git_status))'
style = "bg:git_status fg:text_color"

[python]
format = " [](fg:python)[ $version]($style)[](fg:python)"
style = "bg:python fg:text_color"
version_format = "${raw}"
disabled = false

[nodejs]
format = " [](fg:node)[ $version]($style)[](fg:node)"
style = "bg:node fg:text_color"
version_format = "${raw}"
disabled = false

[time]
disabled = false
format = " [](fg:time)[ $time]($style)[](fg:time)"
time_format = "%H:%M"
style = "bg:time fg:text_color"

[cmd_duration]
format = " [](fg:duration)[ $duration]($style)[](fg:duration)"
style = "bg:duration fg:black"
min_time = 1000

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
